federation_version: 2
subgraphs:
  user:
    routing_url: http://localhost:4001/graphql
    schema:
      file: ../services/user/user.graphql
  review:
    routing_url: http://localhost:4002/graphql
    schema:
      file: ../services/review/review.graphql
